public enum SFXType
{
    UI_ZOOM_IN,
    APP_HOVERING,
    PAUSE_MENU_BUTTON_HOVERING,
    DESTROY_EMEMY_IMPACT,
    EXPLOSION_ENEMY_IMPACT,
    TRASH_ENEMY_IMPACT,
    SHOOTING_SCRIPT_IMPACT,
    APP_OPENING,
    GAME_EXIT,
    PLAYER_HURT_IMPACT,
    GUIDE_OPENING,
    GUIDE_NOTES_HOVERING
}